kind: ServiceAccount
apiVersion: v1
metadata:
  name: sa-VAR_SERVICE_NAME
  namespace: VAR_NAMESPACE_KUBERNETES
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::175174716971:role/eks-staging-VAR_NAMESPACE_KUBERNETES-VAR_SERVICE_NAME
