version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_name_default
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 0.5s
      retries: 5
  mock_server:
    image: mockserver/mockserver:5.15.0
    container_name: project-name-default-mock-server
    ports:
      - 9123:1234
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectationInit.json
      MOCKSERVER_SERVER_PORT: 1234
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
    volumes:
      - ./docker/mockserver:/config
  zookeeper:
    image: wurstmeister/zookeeper
    platform: linux/x86_64
    ports:
      - 2181:2181
    hostname: zookeeper
    volumes:
      - ./.docker/zookeeper/data:/var/lib/zookeeper/data
      - ./.docker/zookeeper/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    platform: linux/arm64
    ports:
      - 9092:9092
    hostname: kafka
    volumes:
      - ./.docker/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:29092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        tp_deal_request_created:1:1
  akhq:
    image: tchiotludo/akhq:dev
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:9092"
          topic-data:
            sort: NEWEST
    ports:
      - 8000:8080
    depends_on:
      - kafka
      - zookeeper
