apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR_SERVICE_NAME
spec:
  template:
    spec:
      containers:
        - name: VAR_SERVICE_NAME
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
