apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR_SERVICE_NAME
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: NotIn
                    values:
                      - workers
