apiVersion: apps/v1
kind: Deployment
metadata:
  name: VAR_SERVICE_NAME
spec:
  template:
    spec:
      containers:
        - name: VAR_SERVICE_NAME
          env:
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
          volumeMounts:
            - name: aws-iam-token
              readOnly: true
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
